name: Deploy Backend

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy hr_client to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: vera
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo /home/vera/vera-erp/erp-deploy/scripts/deploy-backend.sh 2>&1
